import 'package:el_race/core/recruitment/models/requisition.dart';

/// Mock requisitions — TASKS R1 (8–10 records, all states).
///
/// // TODO(backend): Remove when API is wired.
List<Requisition> recruitmentMockRequisitions() {
  final base = DateTime(2026, 4, 1);
  return [
    Requisition(
      id: 'req-001',
      referenceNumber: 'REQ/2026/0001',
      jobTitle: 'Senior Flutter Engineer',
      department: 'Engineering',
      location: 'Dubai',
      vacancies: 2,
      candidateCount: 14,
      offerCount: 1,
      uiStatus: 'OPEN',
      uiStatusLabel: 'Open',
      raisedBy: 'Alex Morgan',
      openedAt: base.add(const Duration(days: 2)),
      candidatesInPipeline: 11,
      pendingOfferCount: 1,
    ),
    Requisition(
      id: 'req-002',
      referenceNumber: 'REQ/2026/0002',
      jobTitle: 'Product Designer',
      department: 'Product',
      location: 'Abu Dhabi',
      vacancies: 1,
      candidateCount: 8,
      offerCount: 0,
      uiStatus: 'HR_MANAGER_APPROVAL',
      uiStatusLabel: 'HR manager approval',
      raisedBy: 'Samira Khan',
      openedAt: base.add(const Duration(days: 5)),
      candidatesInPipeline: 6,
      pendingOfferCount: 0,
    ),
    Requisition(
      id: 'req-003',
      referenceNumber: 'REQ/2026/0003',
      jobTitle: 'HR Business Partner',
      department: 'Human Resources',
      location: 'Dubai',
      vacancies: 1,
      candidateCount: 5,
      offerCount: 0,
      uiStatus: 'OPEN',
      uiStatusLabel: 'Open',
      raisedBy: 'Jordan Lee',
      openedAt: base.add(const Duration(days: 8)),
      candidatesInPipeline: 4,
      pendingOfferCount: 0,
    ),
    Requisition(
      id: 'req-004',
      referenceNumber: 'REQ/2026/0004',
      jobTitle: 'DevOps Engineer',
      department: 'Engineering',
      location: 'Riyadh',
      vacancies: 1,
      candidateCount: 12,
      offerCount: 2,
      uiStatus: 'OPEN',
      uiStatusLabel: 'Open',
      raisedBy: 'Alex Morgan',
      openedAt: base.add(const Duration(days: 12)),
      candidatesInPipeline: 9,
      pendingOfferCount: 1,
    ),
    Requisition(
      id: 'req-005',
      referenceNumber: 'REQ/2026/0005',
      jobTitle: 'Marketing Specialist',
      department: 'Marketing',
      location: 'Sharjah',
      vacancies: 2,
      candidateCount: 0,
      offerCount: 0,
      uiStatus: 'DRAFT',
      raisedBy: 'Samira Khan',
      openedAt: base.add(const Duration(days: 1)),
      candidatesInPipeline: 0,
      pendingOfferCount: 0,
    ),
    Requisition(
      id: 'req-006',
      referenceNumber: 'REQ/2026/0006',
      jobTitle: 'Finance Analyst',
      department: 'Finance',
      location: 'Dubai',
      vacancies: 1,
      candidateCount: 3,
      offerCount: 0,
      uiStatus: 'DRAFT',
      raisedBy: 'Jordan Lee',
      openedAt: base.add(const Duration(days: 0)),
      candidatesInPipeline: 0,
      pendingOfferCount: 0,
    ),
    Requisition(
      id: 'req-007',
      referenceNumber: 'REQ/2026/0007',
      jobTitle: 'Customer Success Manager',
      department: 'Sales',
      location: 'Abu Dhabi',
      vacancies: 1,
      candidateCount: 6,
      offerCount: 1,
      uiStatus: 'CLOSED',
      uiStatusLabel: 'Closed',
      raisedBy: 'Alex Morgan',
      openedAt: base.add(const Duration(days: 40)),
      candidatesInPipeline: 0,
      pendingOfferCount: 0,
    ),
    Requisition(
      id: 'req-008',
      referenceNumber: 'REQ/2026/0008',
      jobTitle: 'IT Support Technician',
      department: 'IT',
      location: 'Dubai',
      vacancies: 2,
      candidateCount: 4,
      offerCount: 0,
      uiStatus: 'CANCELLED',
      raisedBy: 'Samira Khan',
      openedAt: base.add(const Duration(days: 25)),
      candidatesInPipeline: 0,
      pendingOfferCount: 0,
    ),
    Requisition(
      id: 'req-009',
      referenceNumber: 'REQ/2026/0009',
      jobTitle: 'Data Engineer',
      department: 'Engineering',
      location: 'Dubai',
      vacancies: 1,
      candidateCount: 9,
      offerCount: 0,
      uiStatus: 'OPEN',
      uiStatusLabel: 'Open',
      raisedBy: 'Jordan Lee',
      openedAt: base.add(const Duration(days: 18)),
      candidatesInPipeline: 7,
      pendingOfferCount: 0,
    ),
    Requisition(
      id: 'req-010',
      referenceNumber: 'REQ/2026/0010',
      jobTitle: 'Legal Counsel',
      department: 'Legal',
      location: 'Dubai',
      vacancies: 1,
      candidateCount: 2,
      offerCount: 0,
      uiStatus: 'HR_MANAGER_APPROVAL',
      uiStatusLabel: 'HR manager approval',
      raisedBy: 'Alex Morgan',
      openedAt: base.add(const Duration(days: 30)),
      candidatesInPipeline: 2,
      pendingOfferCount: 0,
    ),
  ];
}
